/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockhdmi_cec_driver.h"

static const char* CMockString_HdmiCecAddLogicalAddress = "HdmiCecAddLogicalAddress";
static const char* CMockString_HdmiCecClose = "HdmiCecClose";
static const char* CMockString_HdmiCecGetLogicalAddress = "HdmiCecGetLogicalAddress";
static const char* CMockString_HdmiCecGetPhysicalAddress = "HdmiCecGetPhysicalAddress";
static const char* CMockString_HdmiCecOpen = "HdmiCecOpen";
static const char* CMockString_HdmiCecRemoveLogicalAddress = "HdmiCecRemoveLogicalAddress";
static const char* CMockString_HdmiCecSetLogicalAddress = "HdmiCecSetLogicalAddress";
static const char* CMockString_HdmiCecSetRxCallback = "HdmiCecSetRxCallback";
static const char* CMockString_HdmiCecSetTxCallback = "HdmiCecSetTxCallback";
static const char* CMockString_HdmiCecTx = "HdmiCecTx";
static const char* CMockString_HdmiCecTxAsync = "HdmiCecTxAsync";
static const char* CMockString_buf = "buf";
static const char* CMockString_cbfunc = "cbfunc";
static const char* CMockString_data = "data";
static const char* CMockString_devType = "devType";
static const char* CMockString_handle = "handle";
static const char* CMockString_len = "len";
static const char* CMockString_logicalAddress = "logicalAddress";
static const char* CMockString_logicalAddresses = "logicalAddresses";
static const char* CMockString_num = "num";
static const char* CMockString_physicalAddress = "physicalAddress";
static const char* CMockString_result = "result";

typedef struct _CMOCK_HdmiCecOpen_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int* Expected_handle;

} CMOCK_HdmiCecOpen_CALL_INSTANCE;

typedef struct _CMOCK_HdmiCecClose_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_handle;

} CMOCK_HdmiCecClose_CALL_INSTANCE;

typedef struct _CMOCK_HdmiCecSetLogicalAddress_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_handle;
  int* Expected_logicalAddresses;
  int Expected_num;

} CMOCK_HdmiCecSetLogicalAddress_CALL_INSTANCE;

typedef struct _CMOCK_HdmiCecGetPhysicalAddress_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int Expected_handle;
  unsigned int* Expected_physicalAddress;

} CMOCK_HdmiCecGetPhysicalAddress_CALL_INSTANCE;

typedef struct _CMOCK_HdmiCecAddLogicalAddress_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_handle;
  int Expected_logicalAddresses;

} CMOCK_HdmiCecAddLogicalAddress_CALL_INSTANCE;

typedef struct _CMOCK_HdmiCecRemoveLogicalAddress_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_handle;
  int Expected_logicalAddresses;

} CMOCK_HdmiCecRemoveLogicalAddress_CALL_INSTANCE;

typedef struct _CMOCK_HdmiCecGetLogicalAddress_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_handle;
  int Expected_devType;
  int* Expected_logicalAddress;

} CMOCK_HdmiCecGetLogicalAddress_CALL_INSTANCE;

typedef struct _CMOCK_HdmiCecSetRxCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_handle;
  HdmiCecRxCallback_t Expected_cbfunc;
  void* Expected_data;

} CMOCK_HdmiCecSetRxCallback_CALL_INSTANCE;

typedef struct _CMOCK_HdmiCecSetTxCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_handle;
  HdmiCecTxCallback_t Expected_cbfunc;
  void* Expected_data;

} CMOCK_HdmiCecSetTxCallback_CALL_INSTANCE;

typedef struct _CMOCK_HdmiCecTx_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_handle;
  const unsigned char* Expected_buf;
  int Expected_len;
  int* Expected_result;

} CMOCK_HdmiCecTx_CALL_INSTANCE;

typedef struct _CMOCK_HdmiCecTxAsync_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int Expected_handle;
  const unsigned char* Expected_buf;
  int Expected_len;

} CMOCK_HdmiCecTxAsync_CALL_INSTANCE;

static struct Mockhdmi_cec_driverInstance
{
  CMOCK_MEM_INDEX_TYPE HdmiCecOpen_CallInstance;
  CMOCK_MEM_INDEX_TYPE HdmiCecClose_CallInstance;
  CMOCK_MEM_INDEX_TYPE HdmiCecSetLogicalAddress_CallInstance;
  CMOCK_MEM_INDEX_TYPE HdmiCecGetPhysicalAddress_CallInstance;
  CMOCK_MEM_INDEX_TYPE HdmiCecAddLogicalAddress_CallInstance;
  CMOCK_MEM_INDEX_TYPE HdmiCecRemoveLogicalAddress_CallInstance;
  CMOCK_MEM_INDEX_TYPE HdmiCecGetLogicalAddress_CallInstance;
  CMOCK_MEM_INDEX_TYPE HdmiCecSetRxCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE HdmiCecSetTxCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE HdmiCecTx_CallInstance;
  CMOCK_MEM_INDEX_TYPE HdmiCecTxAsync_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockhdmi_cec_driver_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.HdmiCecOpen_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HdmiCecOpen);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HdmiCecClose_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HdmiCecClose);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HdmiCecSetLogicalAddress_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HdmiCecSetLogicalAddress);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HdmiCecGetPhysicalAddress_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HdmiCecGetPhysicalAddress);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HdmiCecAddLogicalAddress_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HdmiCecAddLogicalAddress);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HdmiCecRemoveLogicalAddress_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HdmiCecRemoveLogicalAddress);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HdmiCecGetLogicalAddress_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HdmiCecGetLogicalAddress);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HdmiCecSetRxCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HdmiCecSetRxCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HdmiCecSetTxCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HdmiCecSetTxCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HdmiCecTx_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HdmiCecTx);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HdmiCecTxAsync_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HdmiCecTxAsync);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockhdmi_cec_driver_Init(void)
{
  Mockhdmi_cec_driver_Destroy();
}

void Mockhdmi_cec_driver_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int HdmiCecOpen(int* handle)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HdmiCecOpen_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HdmiCecOpen);
  cmock_call_instance = (CMOCK_HdmiCecOpen_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HdmiCecOpen_CallInstance);
  Mock.HdmiCecOpen_CallInstance = CMock_Guts_MemNext(Mock.HdmiCecOpen_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecOpen,CMockString_handle);
    if (cmock_call_instance->Expected_handle == NULL)
      { UNITY_TEST_ASSERT_NULL(handle, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_INT_ARRAY(cmock_call_instance->Expected_handle, handle, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HdmiCecOpen(CMOCK_HdmiCecOpen_CALL_INSTANCE* cmock_call_instance, int* handle);
void CMockExpectParameters_HdmiCecOpen(CMOCK_HdmiCecOpen_CALL_INSTANCE* cmock_call_instance, int* handle)
{
  cmock_call_instance->Expected_handle = handle;
}

void HdmiCecOpen_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* handle, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HdmiCecOpen_CALL_INSTANCE));
  CMOCK_HdmiCecOpen_CALL_INSTANCE* cmock_call_instance = (CMOCK_HdmiCecOpen_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HdmiCecOpen_CallInstance = CMock_Guts_MemChain(Mock.HdmiCecOpen_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HdmiCecOpen(cmock_call_instance, handle);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int HdmiCecClose(int handle)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HdmiCecClose_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HdmiCecClose);
  cmock_call_instance = (CMOCK_HdmiCecClose_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HdmiCecClose_CallInstance);
  Mock.HdmiCecClose_CallInstance = CMock_Guts_MemNext(Mock.HdmiCecClose_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecClose,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_handle, handle, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HdmiCecClose(CMOCK_HdmiCecClose_CALL_INSTANCE* cmock_call_instance, int handle);
void CMockExpectParameters_HdmiCecClose(CMOCK_HdmiCecClose_CALL_INSTANCE* cmock_call_instance, int handle)
{
  cmock_call_instance->Expected_handle = handle;
}

void HdmiCecClose_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int handle, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HdmiCecClose_CALL_INSTANCE));
  CMOCK_HdmiCecClose_CALL_INSTANCE* cmock_call_instance = (CMOCK_HdmiCecClose_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HdmiCecClose_CallInstance = CMock_Guts_MemChain(Mock.HdmiCecClose_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HdmiCecClose(cmock_call_instance, handle);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int HdmiCecSetLogicalAddress(int handle, int* logicalAddresses, int num)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HdmiCecSetLogicalAddress_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HdmiCecSetLogicalAddress);
  cmock_call_instance = (CMOCK_HdmiCecSetLogicalAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HdmiCecSetLogicalAddress_CallInstance);
  Mock.HdmiCecSetLogicalAddress_CallInstance = CMock_Guts_MemNext(Mock.HdmiCecSetLogicalAddress_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecSetLogicalAddress,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_handle, handle, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecSetLogicalAddress,CMockString_logicalAddresses);
    if (cmock_call_instance->Expected_logicalAddresses == NULL)
      { UNITY_TEST_ASSERT_NULL(logicalAddresses, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_INT_ARRAY(cmock_call_instance->Expected_logicalAddresses, logicalAddresses, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecSetLogicalAddress,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_num, num, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HdmiCecSetLogicalAddress(CMOCK_HdmiCecSetLogicalAddress_CALL_INSTANCE* cmock_call_instance, int handle, int* logicalAddresses, int num);
void CMockExpectParameters_HdmiCecSetLogicalAddress(CMOCK_HdmiCecSetLogicalAddress_CALL_INSTANCE* cmock_call_instance, int handle, int* logicalAddresses, int num)
{
  cmock_call_instance->Expected_handle = handle;
  cmock_call_instance->Expected_logicalAddresses = logicalAddresses;
  cmock_call_instance->Expected_num = num;
}

void HdmiCecSetLogicalAddress_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int handle, int* logicalAddresses, int num, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HdmiCecSetLogicalAddress_CALL_INSTANCE));
  CMOCK_HdmiCecSetLogicalAddress_CALL_INSTANCE* cmock_call_instance = (CMOCK_HdmiCecSetLogicalAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HdmiCecSetLogicalAddress_CallInstance = CMock_Guts_MemChain(Mock.HdmiCecSetLogicalAddress_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HdmiCecSetLogicalAddress(cmock_call_instance, handle, logicalAddresses, num);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void HdmiCecGetPhysicalAddress(int handle, unsigned int* physicalAddress)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HdmiCecGetPhysicalAddress_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HdmiCecGetPhysicalAddress);
  cmock_call_instance = (CMOCK_HdmiCecGetPhysicalAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HdmiCecGetPhysicalAddress_CallInstance);
  Mock.HdmiCecGetPhysicalAddress_CallInstance = CMock_Guts_MemNext(Mock.HdmiCecGetPhysicalAddress_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecGetPhysicalAddress,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_handle, handle, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecGetPhysicalAddress,CMockString_physicalAddress);
    if (cmock_call_instance->Expected_physicalAddress == NULL)
      { UNITY_TEST_ASSERT_NULL(physicalAddress, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_physicalAddress, physicalAddress, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HdmiCecGetPhysicalAddress(CMOCK_HdmiCecGetPhysicalAddress_CALL_INSTANCE* cmock_call_instance, int handle, unsigned int* physicalAddress);
void CMockExpectParameters_HdmiCecGetPhysicalAddress(CMOCK_HdmiCecGetPhysicalAddress_CALL_INSTANCE* cmock_call_instance, int handle, unsigned int* physicalAddress)
{
  cmock_call_instance->Expected_handle = handle;
  cmock_call_instance->Expected_physicalAddress = physicalAddress;
}

void HdmiCecGetPhysicalAddress_CMockExpect(UNITY_LINE_TYPE cmock_line, int handle, unsigned int* physicalAddress)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HdmiCecGetPhysicalAddress_CALL_INSTANCE));
  CMOCK_HdmiCecGetPhysicalAddress_CALL_INSTANCE* cmock_call_instance = (CMOCK_HdmiCecGetPhysicalAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HdmiCecGetPhysicalAddress_CallInstance = CMock_Guts_MemChain(Mock.HdmiCecGetPhysicalAddress_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HdmiCecGetPhysicalAddress(cmock_call_instance, handle, physicalAddress);
}

int HdmiCecAddLogicalAddress(int handle, int logicalAddresses)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HdmiCecAddLogicalAddress_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HdmiCecAddLogicalAddress);
  cmock_call_instance = (CMOCK_HdmiCecAddLogicalAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HdmiCecAddLogicalAddress_CallInstance);
  Mock.HdmiCecAddLogicalAddress_CallInstance = CMock_Guts_MemNext(Mock.HdmiCecAddLogicalAddress_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecAddLogicalAddress,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_handle, handle, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecAddLogicalAddress,CMockString_logicalAddresses);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_logicalAddresses, logicalAddresses, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HdmiCecAddLogicalAddress(CMOCK_HdmiCecAddLogicalAddress_CALL_INSTANCE* cmock_call_instance, int handle, int logicalAddresses);
void CMockExpectParameters_HdmiCecAddLogicalAddress(CMOCK_HdmiCecAddLogicalAddress_CALL_INSTANCE* cmock_call_instance, int handle, int logicalAddresses)
{
  cmock_call_instance->Expected_handle = handle;
  cmock_call_instance->Expected_logicalAddresses = logicalAddresses;
}

void HdmiCecAddLogicalAddress_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int handle, int logicalAddresses, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HdmiCecAddLogicalAddress_CALL_INSTANCE));
  CMOCK_HdmiCecAddLogicalAddress_CALL_INSTANCE* cmock_call_instance = (CMOCK_HdmiCecAddLogicalAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HdmiCecAddLogicalAddress_CallInstance = CMock_Guts_MemChain(Mock.HdmiCecAddLogicalAddress_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HdmiCecAddLogicalAddress(cmock_call_instance, handle, logicalAddresses);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int HdmiCecRemoveLogicalAddress(int handle, int logicalAddresses)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HdmiCecRemoveLogicalAddress_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HdmiCecRemoveLogicalAddress);
  cmock_call_instance = (CMOCK_HdmiCecRemoveLogicalAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HdmiCecRemoveLogicalAddress_CallInstance);
  Mock.HdmiCecRemoveLogicalAddress_CallInstance = CMock_Guts_MemNext(Mock.HdmiCecRemoveLogicalAddress_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecRemoveLogicalAddress,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_handle, handle, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecRemoveLogicalAddress,CMockString_logicalAddresses);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_logicalAddresses, logicalAddresses, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HdmiCecRemoveLogicalAddress(CMOCK_HdmiCecRemoveLogicalAddress_CALL_INSTANCE* cmock_call_instance, int handle, int logicalAddresses);
void CMockExpectParameters_HdmiCecRemoveLogicalAddress(CMOCK_HdmiCecRemoveLogicalAddress_CALL_INSTANCE* cmock_call_instance, int handle, int logicalAddresses)
{
  cmock_call_instance->Expected_handle = handle;
  cmock_call_instance->Expected_logicalAddresses = logicalAddresses;
}

void HdmiCecRemoveLogicalAddress_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int handle, int logicalAddresses, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HdmiCecRemoveLogicalAddress_CALL_INSTANCE));
  CMOCK_HdmiCecRemoveLogicalAddress_CALL_INSTANCE* cmock_call_instance = (CMOCK_HdmiCecRemoveLogicalAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HdmiCecRemoveLogicalAddress_CallInstance = CMock_Guts_MemChain(Mock.HdmiCecRemoveLogicalAddress_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HdmiCecRemoveLogicalAddress(cmock_call_instance, handle, logicalAddresses);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int HdmiCecGetLogicalAddress(int handle, int devType, int* logicalAddress)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HdmiCecGetLogicalAddress_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HdmiCecGetLogicalAddress);
  cmock_call_instance = (CMOCK_HdmiCecGetLogicalAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HdmiCecGetLogicalAddress_CallInstance);
  Mock.HdmiCecGetLogicalAddress_CallInstance = CMock_Guts_MemNext(Mock.HdmiCecGetLogicalAddress_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecGetLogicalAddress,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_handle, handle, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecGetLogicalAddress,CMockString_devType);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_devType, devType, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecGetLogicalAddress,CMockString_logicalAddress);
    if (cmock_call_instance->Expected_logicalAddress == NULL)
      { UNITY_TEST_ASSERT_NULL(logicalAddress, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_INT_ARRAY(cmock_call_instance->Expected_logicalAddress, logicalAddress, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HdmiCecGetLogicalAddress(CMOCK_HdmiCecGetLogicalAddress_CALL_INSTANCE* cmock_call_instance, int handle, int devType, int* logicalAddress);
void CMockExpectParameters_HdmiCecGetLogicalAddress(CMOCK_HdmiCecGetLogicalAddress_CALL_INSTANCE* cmock_call_instance, int handle, int devType, int* logicalAddress)
{
  cmock_call_instance->Expected_handle = handle;
  cmock_call_instance->Expected_devType = devType;
  cmock_call_instance->Expected_logicalAddress = logicalAddress;
}

void HdmiCecGetLogicalAddress_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int handle, int devType, int* logicalAddress, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HdmiCecGetLogicalAddress_CALL_INSTANCE));
  CMOCK_HdmiCecGetLogicalAddress_CALL_INSTANCE* cmock_call_instance = (CMOCK_HdmiCecGetLogicalAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HdmiCecGetLogicalAddress_CallInstance = CMock_Guts_MemChain(Mock.HdmiCecGetLogicalAddress_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HdmiCecGetLogicalAddress(cmock_call_instance, handle, devType, logicalAddress);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int HdmiCecSetRxCallback(int handle, HdmiCecRxCallback_t cbfunc, void* data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HdmiCecSetRxCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HdmiCecSetRxCallback);
  cmock_call_instance = (CMOCK_HdmiCecSetRxCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HdmiCecSetRxCallback_CallInstance);
  Mock.HdmiCecSetRxCallback_CallInstance = CMock_Guts_MemNext(Mock.HdmiCecSetRxCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecSetRxCallback,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_handle, handle, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecSetRxCallback,CMockString_cbfunc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cbfunc), (void*)(&cbfunc), sizeof(HdmiCecRxCallback_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecSetRxCallback,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HdmiCecSetRxCallback(CMOCK_HdmiCecSetRxCallback_CALL_INSTANCE* cmock_call_instance, int handle, HdmiCecRxCallback_t cbfunc, void* data);
void CMockExpectParameters_HdmiCecSetRxCallback(CMOCK_HdmiCecSetRxCallback_CALL_INSTANCE* cmock_call_instance, int handle, HdmiCecRxCallback_t cbfunc, void* data)
{
  cmock_call_instance->Expected_handle = handle;
  memcpy((void*)(&cmock_call_instance->Expected_cbfunc), (void*)(&cbfunc),
         sizeof(HdmiCecRxCallback_t[sizeof(cbfunc) == sizeof(HdmiCecRxCallback_t) ? 1 : -1])); /* add HdmiCecRxCallback_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_data = data;
}

void HdmiCecSetRxCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int handle, HdmiCecRxCallback_t cbfunc, void* data, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HdmiCecSetRxCallback_CALL_INSTANCE));
  CMOCK_HdmiCecSetRxCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HdmiCecSetRxCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HdmiCecSetRxCallback_CallInstance = CMock_Guts_MemChain(Mock.HdmiCecSetRxCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HdmiCecSetRxCallback(cmock_call_instance, handle, cbfunc, data);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int HdmiCecSetTxCallback(int handle, HdmiCecTxCallback_t cbfunc, void* data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HdmiCecSetTxCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HdmiCecSetTxCallback);
  cmock_call_instance = (CMOCK_HdmiCecSetTxCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HdmiCecSetTxCallback_CallInstance);
  Mock.HdmiCecSetTxCallback_CallInstance = CMock_Guts_MemNext(Mock.HdmiCecSetTxCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecSetTxCallback,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_handle, handle, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecSetTxCallback,CMockString_cbfunc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cbfunc), (void*)(&cbfunc), sizeof(HdmiCecTxCallback_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecSetTxCallback,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HdmiCecSetTxCallback(CMOCK_HdmiCecSetTxCallback_CALL_INSTANCE* cmock_call_instance, int handle, HdmiCecTxCallback_t cbfunc, void* data);
void CMockExpectParameters_HdmiCecSetTxCallback(CMOCK_HdmiCecSetTxCallback_CALL_INSTANCE* cmock_call_instance, int handle, HdmiCecTxCallback_t cbfunc, void* data)
{
  cmock_call_instance->Expected_handle = handle;
  memcpy((void*)(&cmock_call_instance->Expected_cbfunc), (void*)(&cbfunc),
         sizeof(HdmiCecTxCallback_t[sizeof(cbfunc) == sizeof(HdmiCecTxCallback_t) ? 1 : -1])); /* add HdmiCecTxCallback_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_data = data;
}

void HdmiCecSetTxCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int handle, HdmiCecTxCallback_t cbfunc, void* data, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HdmiCecSetTxCallback_CALL_INSTANCE));
  CMOCK_HdmiCecSetTxCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HdmiCecSetTxCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HdmiCecSetTxCallback_CallInstance = CMock_Guts_MemChain(Mock.HdmiCecSetTxCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HdmiCecSetTxCallback(cmock_call_instance, handle, cbfunc, data);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int HdmiCecTx(int handle, const unsigned char* buf, int len, int* result)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HdmiCecTx_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HdmiCecTx);
  cmock_call_instance = (CMOCK_HdmiCecTx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HdmiCecTx_CallInstance);
  Mock.HdmiCecTx_CallInstance = CMock_Guts_MemNext(Mock.HdmiCecTx_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecTx,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_handle, handle, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecTx,CMockString_buf);
    if (cmock_call_instance->Expected_buf == NULL)
      { UNITY_TEST_ASSERT_NULL(buf, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_buf, buf, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecTx,CMockString_len);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_len, len, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecTx,CMockString_result);
    if (cmock_call_instance->Expected_result == NULL)
      { UNITY_TEST_ASSERT_NULL(result, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_INT_ARRAY(cmock_call_instance->Expected_result, result, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HdmiCecTx(CMOCK_HdmiCecTx_CALL_INSTANCE* cmock_call_instance, int handle, const unsigned char* buf, int len, int* result);
void CMockExpectParameters_HdmiCecTx(CMOCK_HdmiCecTx_CALL_INSTANCE* cmock_call_instance, int handle, const unsigned char* buf, int len, int* result)
{
  cmock_call_instance->Expected_handle = handle;
  memcpy((void*)(&cmock_call_instance->Expected_buf), (void*)(&buf),
         sizeof(const unsigned char*[sizeof(buf) == sizeof(const unsigned char*) ? 1 : -1])); /* add const unsigned char* to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_len = len;
  cmock_call_instance->Expected_result = result;
}

void HdmiCecTx_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int handle, const unsigned char* buf, int len, int* result, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HdmiCecTx_CALL_INSTANCE));
  CMOCK_HdmiCecTx_CALL_INSTANCE* cmock_call_instance = (CMOCK_HdmiCecTx_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HdmiCecTx_CallInstance = CMock_Guts_MemChain(Mock.HdmiCecTx_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HdmiCecTx(cmock_call_instance, handle, buf, len, result);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

int HdmiCecTxAsync(int handle, const unsigned char* buf, int len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HdmiCecTxAsync_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HdmiCecTxAsync);
  cmock_call_instance = (CMOCK_HdmiCecTxAsync_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HdmiCecTxAsync_CallInstance);
  Mock.HdmiCecTxAsync_CallInstance = CMock_Guts_MemNext(Mock.HdmiCecTxAsync_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecTxAsync,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_handle, handle, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecTxAsync,CMockString_buf);
    if (cmock_call_instance->Expected_buf == NULL)
      { UNITY_TEST_ASSERT_NULL(buf, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_buf, buf, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_HdmiCecTxAsync,CMockString_len);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_len, len, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HdmiCecTxAsync(CMOCK_HdmiCecTxAsync_CALL_INSTANCE* cmock_call_instance, int handle, const unsigned char* buf, int len);
void CMockExpectParameters_HdmiCecTxAsync(CMOCK_HdmiCecTxAsync_CALL_INSTANCE* cmock_call_instance, int handle, const unsigned char* buf, int len)
{
  cmock_call_instance->Expected_handle = handle;
  memcpy((void*)(&cmock_call_instance->Expected_buf), (void*)(&buf),
         sizeof(const unsigned char*[sizeof(buf) == sizeof(const unsigned char*) ? 1 : -1])); /* add const unsigned char* to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_len = len;
}

void HdmiCecTxAsync_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int handle, const unsigned char* buf, int len, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HdmiCecTxAsync_CALL_INSTANCE));
  CMOCK_HdmiCecTxAsync_CALL_INSTANCE* cmock_call_instance = (CMOCK_HdmiCecTxAsync_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HdmiCecTxAsync_CallInstance = CMock_Guts_MemChain(Mock.HdmiCecTxAsync_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HdmiCecTxAsync(cmock_call_instance, handle, buf, len);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

